### ISSUE TITLE
Milestone 2 - Retro

### ISSUE THREAD

**Issue by anbraten** [project-leek/project-leek#92]

**Comment by anbraten** [comment]
Concrete improvements / actions:

- [ ] check for reviews more often & update the board: put issues on review if ready
- [ ] define a clear sprint-goal & prioritize the issues towards that
- [x] create a shared calendar & be on time for meetings
- [ ] directly ask for help if stuck & present own progress / problems more clearly
- [ ] sometimes long waiting periods as some parts of the code-base were not working => tell the corresponding team-members that you need their work to proceed
